version: "3"

services:

#Building the image from a dockerfile to run the mysqli installation in the image 
 web:
  build:
    #providing path for dockerfile
   context: .
   dockerfile: php_apache_image
  ports:
   - "3333:80"
  depends_on:
   - database

 
#Building the image to add complaints.sql to the docker-entrypoint-initdb.d which will run the sql file to add the table
 database:
  build:
    #providing path for dockerfile
   context: .
   dockerfile: mysqlimage
  command: --default-authentication-plugin=mysql_native_password
  restart: always
